site_name: 999 Solutions - Documentation
nav: 
  - Home: index.md
  - Technical Specifications: tech.md
  - Gallery: gallery.md
  - Future Plans : future.md
  - About Us: about.md

theme: 
  name: readthedocs